version: '3.7'

services:
  app:
    build: .
    container_name: app_php
    volumes:
        - ./src:/var/www

  mysql:
    image: mysql:5.7
    container_name: mysqldb
    command: --innodb_use_native_aio=0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: drowssap
      MYSQL_DATABASE: mysql_test
    volumes:
      - ./db:/var/lib/mysql

  nginx:
    image: nginx:1.17-alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d/
    links:
      - app