version: '3.7'

services:

  api:
    container_name: app_node
    restart: always
    build: .
    depends_on: 
      - mongo
    ports:
      - 8080:3000
    links: 
      - mongo
    volumes:
      - ./:/usr/src/app

  mongo:
    container_name: mongodb
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_DATABASE: mongodb_test
    volumes:
    - ./mongo-volume:/data/db
    